# Generated by Django 4.0 on 2023-05-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todonote_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todonote',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
